### ISSUE TITLE
rename branch from master to devel

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BuildABiocWorkshop#36]
Hi Sean, @seandavi 
Whenever you get a chance, could you rename the branch so that it conforms to Bioconductor guidelines? 
See here for more information: http://contributions.bioconductor.org/branch-rename-faqs.html
Thank you!

**Comment by LiNk-NY** [comment]
Sure, we'd be happy to host it. Thanks!

**Comment by LiNk-NY** [comment]
I sent you an invitation to join the organization. It should be in your email.

**Comment by seandavi** [comment]
It didn't grant me permissions to create repositories. When you get a chance, can you add that for me? I'll need that to transfer the repo.

**Comment by seandavi** [comment]
Should be all yours.

**Comment by LiNk-NY** [comment]
Thank you Sean!
