### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by EricSDavis** [Bioconductor/BuildABiocWorkshop#38]
I was getting this error in the deploy step - "Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128".

In case anyone else encounters this error, adding write permissions to the workflow file fixed it for me. Here is the thread with the solution: https://github.com/JamesIves/github-pages-deploy-action/issues/1110#issuecomment-1124787331

**Comment by LiNk-NY** [comment]
AFAIK this is included in https://github.com/Bioconductor/BuildABiocWorkshop/blob/cf8bc645bf20216ef0992a14aab31ebdd2faf444/.github/workflows/basic_checks.yaml#L79-L84 
Thank you for posting. 
-Marcel
