### ISSUE TITLE
Warnings about various deprecated actions

### ISSUE THREAD

**Issue by amcdavid** [Bioconductor/BuildABiocWorkshop#39]
As of 12 June 2023, we are getting warnings about Node 12 deprecation in the following:

* r-build-and-check `actions/checkout@v2`, `actions/cache@v1`
* docker-build-and-push `actions/checkout@v2`, `docker/setup-buildx-action@79abd3f`

We are getting warnings about `save-state` or `set-output` in docker-build-and-push.  See [this run](https://github.com/OzetteTech/cytoverse-bioc-2023/actions/runs/5248320880), for instance.

It looks like fixes for all of these might just involve bumping the actions version, as I don't see any calls to the deprecated APIs directly in the workflow.  I may take a crack at fixing this when I get a couple hours to play around.

**Comment by LiNk-NY** [comment]
This should be fixed in #40. Let us know if you spot anything else. Thank you! @amcdavid
